# Generated by Django 3.0.5 on 2020-10-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unicorn', 'Unicorn')], default='Unicorn', max_length=10)),
                ('image', models.ImageField(default='thehideout.jpg', upload_to=users.models.Profile.dp_directory_path)),
                ('user_group', models.CharField(choices=[('Pawn', 'Pawn'), ('Rook', 'Rook'), ('Knight', 'Knight'), ('Bishop', 'Bishop'), ('Queen', 'Queen'), ('King', 'King')], default='Pawn', max_length=10)),
                ('school', models.CharField(default='Secret!', max_length=100)),
                ('year_in_school', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Freshman', max_length=10)),
                ('quote', models.CharField(max_length=300)),
                ('about_me', models.TextField(blank=True, default='Well...who cares!? :( JK This is default. Change this! :)')),
                ('reach_me_intro', models.TextField(default='You can reach me thru: (email or socmed accounts)')),
                ('screen_name', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
