# Generated by Django 2.1 on 2020-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='screen_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
